apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: acme 
resources:
  - ../../base/acme
  #- ../../../infrastructure/lib/aws-credentials-sync
  #- ../secret-aws-env.yaml
  # - secret-regcred.yaml
  - release-podinfo.yaml
#patchesStrategicMerge:
#  - podinfo-values.yaml
