apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  releaseName: podinfo
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
  #dependsOn:
  #  - name: other-thing
  #    namespace: other-ns
  interval: 5m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml
  values:
    image:
      repository: ghcr.io/stefanprodan/podinfo # {"$imagepolicy": "flux-system:hallo:name"}
      pullPolicy: IfNotPresent
      tag: "6.0.4" # {"$imagepolicy": "flux-system:hallo:tag"}
      # bump to 6.2.0?
    # pullSecret: "regcred"
    #cache: tcp://redis-master.redis:6379
    #ingress:
    #  enabled: true
    #  annotations:
    #    kubernetes.io/ingress.class: nginx
