apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: hallo
spec:
  filterTags:
    pattern: "^[0-9.]+$"
  imageRepositoryRef:
    name: hallo
  policy:
    numerical:
      order: "asc"
  #  semver:
  #    range: 5.0.x
