apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
# https://github.com/priyanka-ravi/flux-vault-demo/blob/main/clusters/kind/flux-system/kustomization.yaml
patches:
# TODO: Be carful with that one - blew up with OOMKill  
#- patch: |
#    apiVersion: apps/v1
#    kind: Deployment
#    metadata:
#      name: all
#    spec:
#      template:
#        spec:
#          containers:
#            - name: manager
#              resources:
#                limits:
#                  cpu: 250m
#                  memory: 256Mi
#  target:
#    kind: Deployment
- patch: |
    - op: add
      path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/eventSources/items/properties/kind/enum/-
      value: Terraform
  target:
    kind: CustomResourceDefinition
    name: alerts.notification.toolkit.fluxcd.io
- patch: |
    - op: add
      path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/resources/items/properties/kind/enum/-
      value: Terraform
  target:
    kind: CustomResourceDefinition
    name: receivers.notification.toolkit.fluxcd.io
- patch: |
    - op: add
      path: /rules/-
      value:
        apiGroups: [ 'infra.contrib.fluxcd.io' ]
        resources: [ '*' ]
        verbs: [ '*' ]
  target:
    kind: ClusterRole
    name: crd-controller-flux-system
