apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm
            namespace: external-secrets
            key: AWS_ACCESS_KEY_ID
          secretAccessKeySecretRef:
            name: awssm
            namespace: external-secrets
            key: AWS_SECRET_ACCESS_KEY
