kubeProxyReplacement: strict
k8sServiceHost: flux-conductr-control-plane # use master node in kind network
k8sServicePort: 6443                        # use api server port
#hostServices:
#  enabled: false
externalIPs:
  enabled: true
nodePort:
  enabled: true
hostPort:
  enabled: true
image:
  pullPolicy: IfNotPresent
ipam:
  mode: kubernetes
hubble:
  enabled: false
operator:
  # prometheus:
  #   enabled: true
  #   # serviceMonitor:
  #   #   enabled: true
  #   #   labels:
  #   #     release: prometheus
  replicas: 1

prometheus:
  enabled: true
  # serviceMonitor:
  #   enabled: true
  #   labels:
  #     release: prometheus  
