apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: deployment
spec:
  providerRef:
    name: slack-ops
  eventSeverity: info
  # summary: 
  #https://github.com/weaveworks/tf-controller/issues/557
  #exclusionList:
  #  - "failed to verify artifact: computed checksum"     
  eventSources:
    # - image.toolkit.fluxcd.io/v1beta1 ImagePolicy
    # - image.toolkit.fluxcd.io/v1beta1 ImageRepository
    - kind: ImageUpdateAutomation # image.toolkit.fluxcd.io/v1beta1
      name: '*'
      # matchLabels
      # namespace
    - kind: HelmRelease # helm.toolkit.fluxcd.io/v2beta1
      name: '*'
    # - helm.toolkit.fluxcd.io/v2beta1 HelmRelease
    # - source.toolkit.fluxcd.io/v1beta2 Bucket
    # - source.toolkit.fluxcd.io/v1beta2 HelmChart
    # - source.toolkit.fluxcd.io/v1beta2 HelmRepository
    # - source.toolkit.fluxcd.io/v1beta2 OCIRepository
    # - notification.toolkit.fluxcd.io/v1beta1 Receiver
    # - notification.toolkit.fluxcd.io/v1beta1  Alert
    # - notification.toolkit.fluxcd.io/v1beta1 Provider
    # - kind: GitRepository # source.toolkit.fluxcd.io/v1beta2
    #  name: '*'
    - kind: Kustomization # kustomize.toolkit.fluxcd.io/v1
      name: '*'
    - apiVersion: infra.contrib.fluxcd.io/v1alpha1
      kind: Terraform
      name: '*'
