apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: terraform-slack
spec:
  providerRef:
    name: slack-ops
  eventSeverity: info
  eventSources:
    - apiVersion: infra.contrib.fluxcd.io/v1alpha1
      kind: Terraform
      name: '*'
