apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: acme
spec:
  git:
    checkout:
      ref:
        branch: ${gitops_branch:=none}
    commit:
      author:
        email: fluxcdbot@contenreich.de
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: ${gitops_branch:=none}
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: apps-automation
  update:
    path: ./apps/local # ${env:=none} # TODO Hack!
    strategy: Setters

