apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
#- ../secret-aws-env.yaml
- terraform-hello.yaml
- secret-terraform-hello-env.yaml
- external-secret-datadog-env.yaml
- provider-slack-ops-test.yaml
- secret-slack-ops-test.yaml
- automation-acme.yaml
- alert-deployment.yaml
# - alert-terraform.yaml

