apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
#- ../secret-aws-env.yaml
- terraform-hello.yaml
- provider-slack-ops-test.yaml
- secret-slack-ops-test.yaml
- automation-acme.yaml
- alert-ocd.yaml

