apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: slack-ops
spec:
  type: slack
  channel: local-ops
  # webhook address (ignored if secretRef is specified)
  # address: https://...
  # proxy: https://proxy.corp:8080
  # secret containing the webhook address (optional)
  secretRef:
    name: slack-ops-test
