apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: hello
#  namespace: flux-system
spec:
  path: ./
  # Only drift detection - no plan+apply
  # approvePlan: disable
  # Auto w/o drift detection
  approvePlan: auto
  alwaysCleanupRunnerPod: false
  # disableDriftDetection: true

  interval: 1m
  runnerPodTemplate:
    spec:
      envFrom:
        - secretRef:
            name: terraform-hello-env
  #    # image: registry.io/tf-runner:xyz

  sourceRef:
    kind: GitRepository
    name: tf-hello
    namespace: flux-system
