apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: common
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 10m0s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/common
  prune: true
  postBuild:
    substitute:
      gitops_branch: local
      env: testing
      aws_ecr_acc_id: "851715686820"
      aws_acc_id: "597031446072"
      aws_region: eu-central-1
  wait: true
  timeout: 5m0s
